"""empty message

Revision ID: 09e15cec1baf
Revises: 261c7314afca
Create Date: 2020-11-14 23:45:26.368356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e15cec1baf'
down_revision = '261c7314afca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'testthree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('testthree', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
