"""empty message

Revision ID: 261c7314afca
Revises: 
Create Date: 2020-11-14 18:25:27.058891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261c7314afca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revoked_tokens', 'test')
    op.add_column('users', sa.Column('testthree', sa.String(length=120), nullable=True))
    op.drop_column('users', 'testtwo')
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('testtwo', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('users', 'testthree')
    op.add_column('revoked_tokens', sa.Column('test', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
