"""empty message

Revision ID: 609b99d92ad5
Revises: e4d378d2f2d9
Create Date: 2020-07-03 16:24:53.897375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609b99d92ad5'
down_revision = 'e4d378d2f2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_digest', sa.Text(), nullable=True))
    op.drop_column('file', 'file_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('file', 'file_digest')
    # ### end Alembic commands ###
