"""empty message

Revision ID: 8c8313d30ad5
Revises: 
Create Date: 2020-07-03 13:59:47.548139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8313d30ad5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_uuid', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_extension', sa.Integer(), nullable=True),
    sa.Column('date_uploaded', sa.Text(), nullable=True),
    sa.Column('date_modified', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.Text(), nullable=True),
    sa.Column('source_identifier', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('file_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
