"""empty message

Revision ID: e58bb8b6e2db
Revises: 9f5127e13b6f
Create Date: 2020-11-15 21:22:15.955960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58bb8b6e2db'
down_revision = '9f5127e13b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dripbox_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('file', sa.Column('owner', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('public', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'file', 'dripbox_user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'public')
    op.drop_column('file', 'owner')
    op.drop_table('revoked_token')
    op.drop_table('dripbox_user')
    # ### end Alembic commands ###
